### ISSUE TITLE
is it supporting 1.20.5 ?

### ISSUE THREAD

**Issue by PtitLegume** [Lampalon142/LifeLuck#1]
due to >1.20.5 API change on spigot, i wonder if it will work fine on newer version

**Comment by Lampalon142** [comment]
Hello, actualy not but it is in progress :)

**Comment by PtitLegume** [comment]
do you have any discord so i can follow your progression?

**Comment by Lampalon142** [comment]
Yes you can go here : https://discord.gg/xMRpUs7wUn

**Comment by PtitLegume** [comment]
thank you <33

**Comment by Lampalon142** [comment]
No problem :)
